####
#
# This is an example of how you could deploy gecho
# kubectl apply -f gecho.k8s.yaml
#
###
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gecho
  name: gecho
  namespace: applications
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: gecho
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gecho
      name: gecho
    spec:
      containers:
        - image: bjarneo/gecho:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 15
            tcpSocket:
              port: 8080
            timeoutSeconds: 60
          name: gecho
          ports:
            - containerPort: 8080
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 15
            tcpSocket:
              port: 8080
            timeoutSeconds: 60
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 3000
            runAsNonRoot: true
            runAsUser: 1000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
      securityContext:
        fsGroup: 2000
        fsGroupChangePolicy: Always
        runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gecho
  name: gecho
  namespace: applications
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: gecho
  type: NodePort
